# Generated by Django 5.0.6 on 2024-06-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("session_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("session_status", models.BooleanField(default=True)),
                ("session_start_time", models.DateTimeField(auto_now=True)),
                ("session_end_time", models.DateTimeField()),
                ("session_allowed_to_run_code", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("user_username", models.CharField(max_length=100)),
                ("user_email", models.CharField(max_length=200)),
                ("user_password", models.CharField(max_length=72)),
                ("user_firstName", models.CharField(max_length=100)),
                ("user_lastName", models.CharField(max_length=100)),
                ("date_ofBirth", models.DateField()),
                ("phone_number", models.CharField(max_length=100)),
                ("record_date", models.DateTimeField(auto_now=True)),
                ("img_src", models.CharField(max_length=200)),
                (
                    "role_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jwt_api.role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session_user_pool",
            fields=[
                (
                    "session_user_pool_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("flaged", models.BooleanField(default=False)),
                ("code_content", models.TextField()),
                (
                    "session_id_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jwt_api.session",
                    ),
                ),
                (
                    "user_id_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jwt_api.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session_correction_pool",
            fields=[
                (
                    "session_correction_pool_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("correction", models.TextField()),
                ("grade", models.IntegerField(default=0)),
                ("note", models.TextField()),
                (
                    "session_id_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jwt_api.session",
                    ),
                ),
                (
                    "user_id_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jwt_api.users"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="session",
            name="session_starter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jwt_api.users"
            ),
        ),
        migrations.CreateModel(
            name="Users_stats",
            fields=[
                (
                    "users_stats_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("words_per_minute", models.IntegerField(default=0)),
                ("lines_of_code", models.IntegerField(default=0)),
                ("syntax_errors_number", models.IntegerField(default=0)),
                ("code_complexity", models.IntegerField(default=999)),
                (
                    "session_user_pool_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jwt_api.session",
                    ),
                ),
                (
                    "user_id_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jwt_api.users"
                    ),
                ),
            ],
        ),
    ]
