# Generated by Django 5.0.6 on 2024-07-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0003_alter_session_session_end_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refresh_tokens",
            fields=[
                (
                    "id_refresh_token",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("refresh_token", models.CharField(max_length=150)),
                ("first_requester_ip", models.CharField(max_length=16)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="users",
            name="user_email",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
