# Generated by Django 5.0.6 on 2024-07-02 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0006_refresh_tokens_user_id_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refresh_tokens",
            name="user_id_ref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jwt_api.users"
            ),
        ),
    ]
