# Generated by Django 5.0.6 on 2024-07-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0007_alter_refresh_tokens_user_id_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users_devices",
            fields=[
                (
                    "id_users_device",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("device", models.TextField()),
                ("device_ip_address", models.CharField(max_length=120)),
                (
                    "user_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jwt_api.users"
                    ),
                ),
            ],
        ),
    ]
