# Generated by Django 5.0.6 on 2024-07-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0009_remove_refresh_tokens_first_requester_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users_devices",
            name="device_ip_address",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
