# Generated by Django 5.0.6 on 2024-08-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0011_users_devices_is_pc_users_devices_is_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="session_task",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="session_title",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="session_topics",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="Session_users_groupe",
            fields=[
                (
                    "session_users_groupe",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("session_users_groupe_name", models.CharField(max_length=200)),
                (
                    "session_users_groupe_creation_date",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "session_users_groupe_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jwt_api.users"
                    ),
                ),
            ],
        ),
    ]
