# Generated by Django 5.0.6 on 2024-08-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0012_session_session_task_session_session_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session_users_groupe",
            name="session_users_groupe_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="users_stats",
            name="code_complexity",
            field=models.IntegerField(default=0),
        ),
    ]
