# Generated by Django 5.0.6 on 2024-08-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jwt_api",
            "0013_alter_session_users_groupe_session_users_groupe_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Session_stat_tracking_record",
            fields=[
                (
                    "session_stat_tracking_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("session_stat_tracking_total_lines", models.IntegerField(default=0)),
                ("session_stat_tracking_id_errors", models.IntegerField(default=0)),
                (
                    "session_stat_tracking_id_active_studets",
                    models.IntegerField(default=0),
                ),
                (
                    "session_stat_tracking_id_avg_code_comp",
                    models.IntegerField(default=0),
                ),
                (
                    "session_stat_tracking_id_blocked_students",
                    models.IntegerField(default=0),
                ),
                (
                    "session_stat_tracking_Session_Ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jwt_api.session",
                    ),
                ),
            ],
        ),
    ]
