# Generated by Django 5.0.6 on 2024-08-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0014_session_stat_tracking_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session_users_groupe_refs",
            fields=[
                (
                    "user_group_refs_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "user_group_refs_user_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jwt_api.users"
                    ),
                ),
                (
                    "user_group_refs_users_groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jwt_api.session_users_groupe",
                    ),
                ),
            ],
        ),
    ]
