# Generated by Django 5.0.6 on 2024-08-15 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0015_session_users_groupe_refs"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="session_target_group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="jwt_api.session_users_groupe",
            ),
            preserve_default=False,
        ),
    ]
