# Generated by Django 5.0.6 on 2024-08-16 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0016_session_session_target_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Languages",
            fields=[
                ("language_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("language_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="session",
            name="session_language",
            field=models.ForeignKey(
                default="JavaScript",
                on_delete=django.db.models.deletion.CASCADE,
                to="jwt_api.languages",
            ),
            preserve_default=False,
        ),
    ]
