# Generated by Django 5.0.6 on 2024-08-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0017_languages_session_session_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="session_language",
        ),
    ]
