# Generated by Django 5.0.6 on 2024-08-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0021_rename_languages_session_languages_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session_languages",
            old_name="session_languages_id",
            new_name="sessionlanguages_id",
        ),
        migrations.RenameField(
            model_name="session_languages",
            old_name="session_languages_name",
            new_name="sessionlanguages_name",
        ),
    ]
