# Generated by Django 5.0.6 on 2024-08-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "jwt_api",
            "0022_rename_session_languages_id_session_languages_sessionlanguages_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="session_languages",
            new_name="languages",
        ),
        migrations.RenameField(
            model_name="languages",
            old_name="sessionlanguages_id",
            new_name="languages_id",
        ),
        migrations.RenameField(
            model_name="languages",
            old_name="sessionlanguages_name",
            new_name="languages_name",
        ),
    ]
