# Generated by Django 5.0.6 on 2024-08-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0023_rename_session_languages_languages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="jwt_api.languages",
            ),
        ),
    ]
