# Generated by Django 5.0.6 on 2024-08-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0024_alter_session_session_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jwt_api.languages"
            ),
        ),
    ]
