# Generated by Django 5.0.6 on 2024-08-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0025_alter_session_session_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="languages",
            name="languages_id",
        ),
        migrations.AddField(
            model_name="languages",
            name="lang_id",
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
