# Generated by Django 5.0.6 on 2024-08-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0026_remove_languages_languages_id_languages_lang_id"),
    ]

    operations = []
