# Generated by Django 5.0.6 on 2024-08-16 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0027_auto_20240816_1550"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="languages",
            name="lang_id",
        ),
        migrations.RemoveField(
            model_name="session",
            name="session_language",
        ),
        migrations.AddField(
            model_name="languages",
            name="languages_id",
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="session_language_ref",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="jwt_api.languages",
            ),
            preserve_default=False,
        ),
    ]
