# Generated by Django 5.0.6 on 2024-08-16 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0029_remove_session_session_language_ref_delete_languages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Languages",
            fields=[
                (
                    "languages_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("languages_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="session",
            name="session_language_ref",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="jwt_api.languages",
            ),
            preserve_default=False,
        ),
    ]
