# Generated by Django 5.0.6 on 2024-08-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0031_sessionmetricshardrecotd"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="sessionMetricsHardRecotd",
            new_name="sessionMetricsHardRecord",
        ),
    ]
