# Generated by Django 5.0.6 on 2024-08-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0032_rename_sessionmetricshardrecotd_sessionmetricshardrecord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="sessionMetricsHardRecord",
        ),
    ]
