# Generated by Django 5.0.6 on 2024-08-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0036_alter_session_session_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_title",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
