# Generated by Django 5.0.6 on 2024-08-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0037_alter_session_session_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
