# Generated by Django 5.0.6 on 2024-08-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_api", "0043_remove_session_user_pool_session_id_ref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session_user_tracking_record",
            name="Session_user_tracking_record_activity_ends_at",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="session_user_tracking_record",
            name="Session_user_tracking_record_activity_starts_at",
            field=models.DateField(null=True),
        ),
    ]
