# Generated by Django 5.0.6 on 2024-08-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jwt_api",
            "0045_alter_session_user_tracking_record_session_user_tracking_record_errors_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="session_user_tracking_record",
            name="Session_user_tracking_record_summarized_word",
            field=models.TextField(default=""),
        ),
    ]
