# Generated by Django 5.0.6 on 2024-08-30 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "jwt_api",
            "0046_session_user_tracking_record_session_user_tracking_record_summarized_word",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionmetricshardrecord",
            old_name="sessionMetric_totalerrors",
            new_name="sessionMetric_avgerrors",
        ),
        migrations.RenameField(
            model_name="sessionmetricshardrecord",
            old_name="sessionMetric_totallines",
            new_name="sessionMetric_avglines",
        ),
        migrations.RenameField(
            model_name="sessionmetricshardrecord",
            old_name="sessionMetric_totalwordswriten",
            new_name="sessionMetric_avgwordswriten",
        ),
    ]
